name: Gerar Slides PDF

on:
  push:
    paths:
      - "presentation.md"
      - "*.md"
      - "**/*.md"

jobs:
  build-slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    #   - name: Instalar Pandoc
    #     run: sudo apt-get update && sudo apt-get install -y pandoc texlive

    #   - name: Converter Markdown em PDF
    #     run: |
    #       pandoc docs/presentation.md -o slides.pdf --slide-level=2 --pdf-engine=xelatex

      - name: Converter Markdown em PDF usando Docker
        run: |
          docker run --rm \
            --volume "$(pwd):/data" \
            pandoc/latex \
            presentation.md -o slides.pdf --slide-level=2

      - name: Publicar Artefato
        uses: actions/upload-artifact@v4
        with:
          name: slides-pdf
          path: slides.pdf
